apiVersion: v1 
kind: Service 
metadata:
  name: flask-app-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: flask-app-port
      port: 8080
      targetPort: 8081
      nodePort: 32525